name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Samyak-777
          include_all_commits: true
          count_private: true
          show_icons: true
          hide_border: false
          theme: dark
          token: ${{ secrets.GH_STATS_TOKEN }}
